In [1]:
import numpy as np
from scipy.linalg import lu


a = np.mat('2, 4; 6, 8; 8, 0')
print(a)

aT = np.transpose(a)
print(aT)

b = 2*np.eye(3)
print(b)

c = b*a
print(c)

l = lu(a)
print(l)

[[2 4]
 [6 8]
 [8 0]]
[[2 6 8]
 [4 8 0]]
[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]
[[ 4.  8.]
 [12. 16.]
 [16.  0.]]
(array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]]), array([[1.  , 0.  ],
       [0.75, 1.  ],
       [0.25, 0.5 ]]), array([[8., 0.],
       [0., 8.]]))
